// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6VlNJUeSm9C6wmkyp4234BOgKEIi6wSw',
    appId: '1:801148721359:web:cf4686a04a2b4604f4bfba',
    messagingSenderId: '801148721359',
    projectId: 'getiproject-naranggeti',
    authDomain: 'getiproject-naranggeti.firebaseapp.com',
    databaseURL: 'https://getiproject-naranggeti-default-rtdb.firebaseio.com',
    storageBucket: 'getiproject-naranggeti.appspot.com',
    measurementId: 'G-E09K2RP7M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Nx2r-dR0rY_n0wdiH8V0Sxku7fkkmiI',
    appId: '1:801148721359:android:4cc25db1003a302cf4bfba',
    messagingSenderId: '801148721359',
    projectId: 'getiproject-naranggeti',
    databaseURL: 'https://getiproject-naranggeti-default-rtdb.firebaseio.com',
    storageBucket: 'getiproject-naranggeti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8vykFceMeF3Y0aaWvNY4b4XwM5MQWOFg',
    appId: '1:801148721359:ios:28d49b9fe6efc480f4bfba',
    messagingSenderId: '801148721359',
    projectId: 'getiproject-naranggeti',
    databaseURL: 'https://getiproject-naranggeti-default-rtdb.firebaseio.com',
    storageBucket: 'getiproject-naranggeti.appspot.com',
    androidClientId: '801148721359-8u33ibdq5kl67pem128msua14h0a04d4.apps.googleusercontent.com',
    iosClientId: '801148721359-r4r2v3cq0de37cigsf9o1go7aj3m4ugl.apps.googleusercontent.com',
    iosBundleId: 'com.example.somacProjectFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8vykFceMeF3Y0aaWvNY4b4XwM5MQWOFg',
    appId: '1:801148721359:ios:1de4cc8fad52e3a4f4bfba',
    messagingSenderId: '801148721359',
    projectId: 'getiproject-naranggeti',
    databaseURL: 'https://getiproject-naranggeti-default-rtdb.firebaseio.com',
    storageBucket: 'getiproject-naranggeti.appspot.com',
    androidClientId: '801148721359-8u33ibdq5kl67pem128msua14h0a04d4.apps.googleusercontent.com',
    iosClientId: '801148721359-aedmdrvekgjrqu0q0eka3ti23ojo4el3.apps.googleusercontent.com',
    iosBundleId: 'com.example.somacProjectFlutter.RunnerTests',
  );
}
